In [2]:
import pandas as pd

In [5]:
customers = pd.read_csv("train/df_Customers.csv")
order_items = pd.read_csv("train/df_OrderItems.csv")
orders = pd.read_csv("train/df_Orders.csv")
payments = pd.read_csv("train/df_Payments.csv")
products = pd.read_csv("train/df_Products.csv")

In [7]:
print("Customers shape:", customers.shape)
print("Order Items shape:", order_items.shape)
print("Orders shape:", orders.shape)
print("Payments shape:", payments.shape)
print("Products shape:", products.shape)

Customers shape: (89316, 4)
Order Items shape: (89316, 5)
Orders shape: (89316, 7)
Payments shape: (89316, 5)
Products shape: (89316, 6)

In [11]:
for name, df in [("Customers", customers), ("Order Items", order_items), ("Orders", orders), ("Payments", payments), ("Products", products)]:
    print(f"\n{name} DataFrame Info:")
    print(df.info())
    print(f"\n{name} DataFrame Description:")
    print(df.describe())
    print(f"\n{name} Missing Values:")
    print(df.isna().sum())
    print(f"\n{name} Duplicated Rows:")
    print(df.duplicated().sum())

Customers DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               89316 non-null  str
 1   customer_zip_code_prefix  89316 non-null  int64
 2   customer_city             89316 non-null  str
 3   customer_state            89316 non-null  str
dtypes: int64(1), str(3)
memory usage: 2.7 MB
None

Customers DataFrame Description:
       customer_zip_code_prefix
count              89316.000000
mean               40499.471080
std                31194.386361
min                 1003.000000
25%                 9785.000000
50%                35480.000000
75%                70040.000000
max                99990.000000

Customers Missing Values:
customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Customers Duplicated Rows:
0

Order Items DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          89316 non-null  str
 1   product_id        89316 non-null  str
 2   seller_id         89316 non-null  str
 3   price             89316 non-null  float64
 4   shipping_charges  89316 non-null  float64
dtypes: float64(2), str(3)
memory usage: 3.4 MB
None

Order Items DataFrame Description:
              price  shipping_charges
count  89316.000000      89316.000000
mean     340.900543         44.283210
std      557.459897         37.672491
min        0.850000          0.000000
25%       59.650000         20.110000
50%      136.900000         35.055000
75%      399.200000         57.190000
max     6735.000000        409.680000

Order Items Missing Values:
order_id            0
product_id          0
seller_id           0
price               0
shipping_charges    0
dtype: int64

Order Items Duplicated Rows:
0

Orders DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       89316 non-null  str
 1   customer_id                    89316 non-null  str
 2   order_status                   89316 non-null  str
 3   order_purchase_timestamp       89316 non-null  str
 4   order_approved_at              89307 non-null  str
 5   order_delivered_timestamp      87427 non-null  str
 6   order_estimated_delivery_date  89316 non-null  str
dtypes: str(7)
memory usage: 4.8 MB
None

Orders DataFrame Description:
            order_id   customer_id order_status order_purchase_timestamp  \
count          89316         89316        89316                    89316
unique         89316         89316            7                    72775
top     Axfy13Hk4PIk  hCT0x9JiGXBQ    delivered      2017-08-08 20:26:31
freq               1             1        87428                       87

          order_approved_at order_delivered_timestamp  \
count                 89307                     87427
unique                68215                     71143
top     2017-08-08 20:43:31       2017-08-14 12:46:18
freq                     87                        87

       order_estimated_delivery_date
count                          89316
unique                           444
top                       2017-12-20
freq                             500

Orders Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
dtype: int64

Orders Duplicated Rows:
0

Payments DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              89316 non-null  str
 1   payment_sequential    89316 non-null  int64
 2   payment_type          89316 non-null  str
 3   payment_installments  89316 non-null  int64
 4   payment_value         89316 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.4 MB
None

Payments DataFrame Description:
       payment_sequential  payment_installments  payment_value
count        89316.000000          89316.000000   89316.000000
mean             1.099646              2.965717     268.657190
std              0.772658              2.796406     344.409566
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      84.340000
50%              1.000000              2.000000     171.860000
75%              1.000000              4.000000     313.530000
max             29.000000             24.000000    7274.880000

Payments Missing Values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Payments Duplicated Rows:
0

Products DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 89316 entries, 0 to 89315
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             89316 non-null  str
 1   product_category_name  89008 non-null  str
 2   product_weight_g       89301 non-null  float64
 3   product_length_cm      89301 non-null  float64
 4   product_height_cm      89301 non-null  float64
 5   product_width_cm       89301 non-null  float64
dtypes: float64(4), str(2)
memory usage: 4.1 MB
None

Products DataFrame Description:
       product_weight_g  product_length_cm  product_height_cm  \
count      89301.000000       89301.000000       89301.000000
mean        2087.068129          30.220658          16.559423
std         3747.039215          16.110199          13.388514
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1800.000000          38.000000          20.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count       89301.00000
mean           23.03421
std            11.68828
min             6.00000
25%            15.00000
50%            20.00000
75%            30.00000
max           118.00000

Products Missing Values:
product_id                 0
product_category_name    308
product_weight_g          15
product_length_cm         15
product_height_cm         15
product_width_cm          15
dtype: int64

Products Duplicated Rows:
61865

In [12]:
print("Total product rows: ", len(products))
print("Unique product IDs: ", products['product_id'].nunique())
print("Duplicated product IDs: ", products['product_id'].duplicated().sum())

Total product rows:  89316
Unique product IDs:  27451
Duplicated product IDs:  61865

In [ ]:
print("Customer")
print("Rows: ", len(customers))
print("Unique customer IDs: ", customers['customer_id'].nunique())
print("Duplicated customer IDs: ", customers['customer_id'].duplicated())

print("\nOrder Items")
print("Rows: ", len(order_items))
print("Unique order item IDs: ", order_items['order_item_id'].nunique())
print("Duplicated order item IDs: ", order_items['order_item_id'].duplicated())

Customer
Rows:  89316
Unique customer IDs:  89316
Duplicated customer IDs:  0        False
1        False
2        False
3        False
4        False
         ...
89311    False
89312    False
89313    False
89314    False
89315    False
Name: customer_id, Length: 89316, dtype: bool

In [17]:
print("Product rows:", len(products))
print("Unique product IDs:", products["product_id"].nunique())
print("Duplicated product IDs:", products["product_id"].duplicated().sum())

print("Order rows:", len(orders))
print("Unique order IDs:", orders["order_id"].nunique())
print("Duplicated order IDs:", orders["order_id"].duplicated().sum())

print("Order Item rows:", len(order_items))
print("Unique order IDs in Order Items:", order_items["order_id"].nunique())

Product rows: 89316
Unique product IDs: 27451
Duplicated product IDs: 61865
Order rows: 89316
Unique order IDs: 89316
Duplicated order IDs: 0
Order Item rows: 89316
Unique order IDs in Order Items: 89316

In [19]:
print("Customer IDs in Order:", orders["customer_id"].nunique())
print("Customer IDs in Customers:", customers["customer_id"].nunique())

print(
    "Orders with customer IDs not found in Customers:", 
    (~orders["customer_id"].isin(customers["customer_id"])).sum()
)

print(
    "Order IDs in Order Items not found in Orders:",
    (~order_items["order_id"].isin(orders["order_id"])).sum()
)

print(
    "Product IDs in Order Items not found in Products:",
    (~order_items["product_id"].isin(products["product_id"])).sum()
)

Customer IDs in Order: 89316
Customer IDs in Customers: 89316
Orders with customer IDs not found in Customers: 0
Order IDs in Order Items not found in Orders: 0
Product IDs in Order Items not found in Products: 0

In [21]:
orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_timestamp',
 'order_estimated_delivery_date']

In [23]:
orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_timestamp',
 'order_estimated_delivery_date']

In [24]:
products.columns.tolist()

['product_id',
 'product_category_name',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm']

In [26]:
customers.columns.tolist()

['customer_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

In [28]:
orders["order_status"].value_counts()

#orders["order_status"].value_counts(normalize=True) * 100

order_status
delivered      87428
shipped          936
canceled         409
processing       273
invoiced         266
unavailable        2
approved           2
Name: count, dtype: int64

In [ ]:
orders.isna().sum()
order_items.isna().sum()
products.isna().sum()
customers.isna().sum()

customer_id                 0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [35]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_timestamp        str
order_estimated_delivery_date    str
dtype: object

In [37]:
date_columns = [
    "order_purchase_timestamp", 
    "order_approved_at", 
    "order_delivered_timestamp", 
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_timestamp        datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [38]:
orders["delivery_days"] = (orders["order_delivered_timestamp"] - orders["order_purchase_timestamp"]).dt.days

In [39]:
orders[[
    "order_id", 
    "order_purchase_timestamp",
    "order_delivered_timestamp", 
    "delivery_days"
]].head()

,order_id,order_purchase_timestamp,order_delivered_timestamp,delivery_days
0,Axfy13Hk4PIk,2017-10-22 18:57:54,2017-10-26 22:19:52,4.0
1,v6px92oS8cLG,2018-06-20 21:40:31,2018-07-03 22:51:22,13.0
2,Ulpf9skrhjfm,2018-02-16 16:19:31,2018-02-27 01:29:50,10.0
3,bwJVWupf2keN,2018-08-18 18:04:29,2018-08-27 20:03:51,9.0
4,Dd0QnrMk9Cj5,2017-12-22 16:44:04,2018-01-05 19:22:49,14.0

In [40]:
orders["delivery_days"].describe()

count    87427.000000
mean        11.969129
std          9.277678
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

In [41]:
(orders["delivery_days"] < 0).sum()

np.int64(0)

In [42]:
orders[orders["delivery_days"] == orders ["delivery_days"].max()][[
    "order_id", 
    "customer_id",
    "order_purchase_timestamp", 
    "order_delivered_timestamp",
    "order_estimated_delivery_date", 
    "delivery_days"]]

,order_id,customer_id,order_purchase_timestamp,order_delivered_timestamp,order_estimated_delivery_date,delivery_days
571,pWRjBubXBYdq,IgFTw1gGD2PM,2017-02-21 23:31:27,2017-09-19 14:36:39,2017-03-22,209.0

In [48]:
orders["delivery_delay_days"] = (
    orders["order_delivered_timestamp"] - orders["order_estimated_delivery_date"]).dt.days

In [49]:
orders[[
    "order_id",
    "order_delivered_timestamp",
    "order_estimated_delivery_date",
    "delivery_delay_days"
]].head()

,order_id,order_delivered_timestamp,order_estimated_delivery_date,delivery_delay_days
0,Axfy13Hk4PIk,2017-10-26 22:19:52,2017-11-09,-14.0
1,v6px92oS8cLG,2018-07-03 22:51:22,2018-07-24,-21.0
2,Ulpf9skrhjfm,2018-02-27 01:29:50,2018-03-08,-9.0
3,bwJVWupf2keN,2018-08-27 20:03:51,2018-09-19,-23.0
4,Dd0QnrMk9Cj5,2018-01-05 19:22:49,2018-01-18,-13.0

In [50]:
orders["delivery_delay_days"].describe()

count    87427.000000
mean       -12.132442
std         10.041470
min       -147.000000
25%        -17.000000
50%        -13.000000
75%         -7.000000
max        188.000000
Name: delivery_delay_days, dtype: float64

In [51]:
orders[orders["delivery_delay_days"] == orders["delivery_delay_days"].max()][[
    "order_id",
    "order_purchase_timestamp",
    "order_delivered_timestamp",
    "order_estimated_delivery_date",
    "delivery_days",
    "delivery_delay_days"
]]

,order_id,order_purchase_timestamp,order_delivered_timestamp,order_estimated_delivery_date,delivery_days,delivery_delay_days
68448,I7Uy2GUAWB08,2018-02-23 14:57:35,2018-09-19 23:24:07,2018-03-15,208.0,188.0

In [52]:
orders["delivered_on_time"] = (
    orders["delivery_delay_days"] <= 0
)

In [53]:
orders[[
    "order_id",
    "delivery_delay_days",
    "delivered_on_time"
]].head(10)

       order_id  delivery_delay_days  delivered_on_time
0  Axfy13Hk4PIk                -14.0               True
1  v6px92oS8cLG                -21.0               True
2  Ulpf9skrhjfm                 -9.0               True
3  bwJVWupf2keN                -23.0               True
4  Dd0QnrMk9Cj5                -13.0               True
5  VjTVGzqe8U6R                -11.0               True
6  xNba906m4TM1                 -9.0               True
7  VEDSMTavbQwk                 18.0              False
8  DzNM8wrcMGFH                 -3.0               True
9  NpJz7zF9U1ae                -20.0               True

In [55]:
orders["delivered_on_time"].value_counts()

delivered_on_time
True     81822
False     7494
Name: count, dtype: int64

In [56]:
orders["delivered_on_time"].value_counts(normalize=True) * 100

delivered_on_time
True     91.609566
False     8.390434
Name: proportion, dtype: float64

In [59]:
orders["delivered_on_time"] = (
    orders["delivery_delay_days"] <= 0
)

orders["delivery_delay_days"].isna().sum()
orders["delivered_on_time"].isna().sum()

np.int64(0)

In [60]:
orders["delivered_on_time"] = orders["delivery_delay_days"].apply(
    lambda x: True if x <= 0 else False if x > 0 else None
)

In [62]:
orders["delivered_on_time"].value_counts(dropna=False)
orders["delivered_on_time"].value_counts(normalize=True, dropna=True) * 100

delivered_on_time
True     93.588937
False     6.411063
Name: proportion, dtype: float64

In [63]:
orders.loc[
    orders["delivered_on_time"] == False,
    "delivery_delay_days"
].describe()

count    5605.000000
mean       10.453167
std        13.685353
min         1.000000
25%         3.000000
50%         7.000000
75%        13.000000
max       188.000000
Name: delivery_delay_days, dtype: float64